# Generated by Django 3.1 on 2020-12-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_is_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
